[book]
authors = ["rhv9"]
language = "en"
multilingual = false
src = "pages"
title = "Microsoft Azure"

[preprocessor.last_modified]
command = "python last_modified.py"

[output.html]
git-repository-url = "https://github.com/rhv9/book"
additional-js = ["custom.js"]